exclude: 'notebooks/'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: double-quote-string-fixer
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: ['--autofix']
# -   repo: https://github.com/lorenzwalthert/precommit
#     rev: v0.3.0
#     hooks:
#     -   id: spell-check
-   repo: https://github.com/terrencepreilly/darglint
    rev: master
    hooks:
    -   id: darglint
        language_version: python3
# HAVE TO TEST THIS DOES WHAT IS EXPECTED
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.940
#     hooks:
#       - id: mypy
#         additional_dependencies:
#           - types-dataclasses ~= 0.6.5
#           - types-PyYAML ~= 6.0.8
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/john-hen/Flake8-pyproject
    rev: 1.1.0
    hooks:
    -   id: Flake8-pyproject
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [file,python]
        name: isort (python)
# ONLY WORKS WITH POETRY SETUP. WE AREN'T CURRENLTY USING POETRY
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#     rev: v1.2.4
#     hooks:
#     -   id: python-safety-dependencies-check
#         files: pyproject.toml
## UNTESTED
# -   repo: https://github.com/sqlfluff/sqlfluff
#     rev: 0.13.2
#     hooks:
#       - id: sqlfluff-lint
#         name: sqlfluff-lint
#         entry: sqlfluff lint
#         language: python
#         description: 'Lints sql files with `SQLFluff`'
#         types: [sql]
#         require_serial: true
#         additional_dependencies: []
#       - id: sqlfluff-fix
#         name: sqlfluff-fix
#         # Needs to use "--force" to disable confirmation
#         # By default all the rules are applied
#         entry: sqlfluff fix --force
#         language: python
#         description: 'Fixes sql lint errors with `SQLFluff`'
#         types: [sql]
#         require_serial: true
#         additional_dependencies: []
